### ISSUE TITLE
Screenshot on timeout?

### ISSUE THREAD

**Issue by chris-dura** [Huddle/PhantomCSS#108]
I'm trying to generate a screen capture whenever a `waitFor` times out... the native `casper.capture()` method seems to work, but `phantomcss.screenshot()` does not.
I guess I'm not going to try and compare "timeout" screenshots, so the native method is probably better to use anyway, but would you expect `phantomcss.screenshot()` to work in this case?

```js
/*
 * When a waitFor function times-out, log the error and save a screenshot 
 * of the UI in its current state.
 */
casper.on('waitFor.timeout', function() {
    casper.capture('timeout.png'); // this works
    phantomcss.screenshot('body', 'timeout'); // this doesn't
    this.log('A waitFor timed out', 'warning');
});
```

**Comment by jamescryer** [comment]
casper.capture is better for this case, but yeah, I would expect it to work.

The only real difference between the two is that phantomcss.screenshot internally uses a small wait, so to ensure that the log happens after the PhantomCSS capture you'll have to wrap it in a casper.then

```
casper.on('waitFor.timeout', function() {
    casper.capture('timeout.png'); // this works
    phantomcss.screenshot('body', 'timeout'); // this doesn't
    casper.then(function(){ casper.log('A waitFor timed out', 'warning'); });
});
```

It's also possible that the thread is returning before the screenshot is taken (because of the wait).

**Comment by chris-dura** [comment]
> It's also possible that the thread is returning before the screenshot is taken (because of the wait).

I suspected this as well.

**Comment by jamescryer** [comment]
Closing issue because there are no obvious changes required to the library.
