### ISSUE TITLE
New screenshot generated when expected image already exists

### ISSUE THREAD

**Issue by fusionfox** [Huddle/PhantomCSS#167]
We have a number of screenshot comparison tests using PhantomCSS and they work for us really well, but I've observed that every so often our test run starts generating new expected images with the filename incremented, even though a reference image already exists.

For example, for a long time we had a test that captured the screenshot `screenshots/global_nav_0.expected.png`, but now every time the test suite is run this is ignored and a new image is created at `screenshots/global_nav_2.expected.png` even though there are no other images with this filename.

**Comment by thatblairguy** [comment]
I've encountered this problem myself. It turns out that by default, the snapshot images use the name you provide in the screenshot() call, and then append the index into the overall sequence set of tests.  What I suspect is happening to your tests is that initially, "global_nav" was your first test (index 0), and now it's your third (index 2).

Assuming that's your situation, you can change that behavior by supplying a fileNameGetter function when you call phantomcss.init().  The sample function in the readme eliminates the number, but puts the burden on you to guarantee that snapshot names are unique.

**Comment by fusionfox** [comment]
Seems like you're right; if I run all of my tests it generates a `global_nav_3.expected.png` but if I run just that test in isolation it generates a `global_nav_0.expected.png`.

Disappointing but for now I'll take your advice and name the screenshots manually.

**Comment by thatblairguy** [comment]
FWIW, there's also a fileNameGetter() callback which you can override in the init() call. The example in the README just removes the sequence number, but if need be, you could use that to do something more sophisticated..

**Comment by jamescryer** [comment]
Yeah, I see this can be a bit annoying - it's there to ensure uniqueness.  I would recommend using the fileNameGetter callback for custom naming in non-trivial test suites
