### ISSUE TITLE
PhantomCSS is moving the HTML elements around

### ISSUE THREAD

**Issue by eugenefedoto** [Huddle/PhantomCSS#189]
Edit: I discovered this issue is only happening with esfiddle.net.

First time doing visual regression testing.

Problem: when I use a visual regression testing tool such as PhantomCSS, the screenshots produced contain the website with dramatically moved HTML elements.

Problem image:
![Image of <nav> by PhantomCSS](http://i.imgur.com/OsTQ4wX.png)

How it should really look like:

![Actual <nav>](http://i.imgur.com/72bbSlY.png)

Tools: PhantomCSS. The same problem happens with BackstopJS.
URL: http://esfiddle.net/

What can I do to prevent the problem image?

**Comment by jamescryer** [comment]
Its because you're using the `flex` CSS property.  Unfortunately PhantomJS doesn't support flex. Alternatives?, PhantomCSS with SlimerJS should work https://github.com/Huddle/PhantomCSS#slimerjs. I'm not sure if any VRT tooling is available for in Chrome headless yet, but worth a look. You could also try https://github.com/webdriverio/webdrivercss.
